/**
 * Otreeba Open Cannabis API
 * This is an open, canonical database of cannabis seed companies, strains, brands, products, retailers, and studies from [Otreeba](https://otreeba.com). It is written on the OpenAPI Specification AKA Swagger. You can find out more about the Open API Initiative at [https://www.openapis.org/](https://www.openapis.org), or more info on Swagger at [http://swagger.io/](http://swagger.io/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@otreeba.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGInline_response_200_1_meta.h
 * 
 * Gets the current list of Seed Comapnies.
 */

#ifndef SWGInline_response_200_1_meta_H_
#define SWGInline_response_200_1_meta_H_

#include <QJsonObject>


#include "SWGPagination.h"

#include "SWGObject.h"


namespace Swagger {

class SWGInline_response_200_1_meta: public SWGObject {
public:
    SWGInline_response_200_1_meta();
    SWGInline_response_200_1_meta(QString* json);
    virtual ~SWGInline_response_200_1_meta();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGInline_response_200_1_meta* fromJson(QString &jsonString);

    SWGPagination* getPagination();
    void setPagination(SWGPagination* pagination);


private:
    SWGPagination* pagination;
};

} /* namespace Swagger */

#endif /* SWGInline_response_200_1_meta_H_ */
