/**
 * Otreeba Open Cannabis API
 * This is an open, canonical database of cannabis seed companies, strains, brands, products, retailers, and studies from [Otreeba](https://otreeba.com). It is written on the OpenAPI Specification AKA Swagger. You can find out more about the Open API Initiative at [https://www.openapis.org/](https://www.openapis.org), or more info on Swagger at [http://swagger.io/](http://swagger.io/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@otreeba.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGStrain.h
 * 
 * 
 */

#ifndef SWGStrain_H_
#define SWGStrain_H_

#include <QJsonObject>


#include "SWGObject.h"
#include <QDateTime>
#include <QList>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGStrain: public SWGObject {
public:
    SWGStrain();
    SWGStrain(QString* json);
    virtual ~SWGStrain();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGStrain* fromJson(QString &jsonString);

    QString* getName();
    void setName(QString* name);

    QString* getOcpc();
    void setOcpc(QString* ocpc);

    SWGObject* getSeedCompany();
    void setSeedCompany(SWGObject* seed_company);

    QString* getQr();
    void setQr(QString* qr);

    QString* getUrl();
    void setUrl(QString* url);

    QString* getImage();
    void setImage(QString* image);

    SWGObject* getLineage();
    void setLineage(SWGObject* lineage);

    SWGObject* getGenetics();
    void setGenetics(SWGObject* genetics);

    QList<QString*>* getChildren();
    void setChildren(QList<QString*>* children);

    QDateTime* getCreatedAt();
    void setCreatedAt(QDateTime* created_at);

    QDateTime* getUpdatedAt();
    void setUpdatedAt(QDateTime* updated_at);


private:
    QString* name;
    QString* ocpc;
    SWGObject* seed_company;
    QString* qr;
    QString* url;
    QString* image;
    SWGObject* lineage;
    SWGObject* genetics;
    QList<QString*>* children;
    QDateTime* created_at;
    QDateTime* updated_at;
};

} /* namespace Swagger */

#endif /* SWGStrain_H_ */
