#import <Foundation/Foundation.h>
#import "SWGEdible.h"
#import "SWGInlineResponse2002.h"
#import "SWGApi.h"

/**
* Otreeba Open Cannabis API
* This is an open, canonical database of cannabis seed companies, strains, brands, products, retailers, and studies from [Otreeba](https://otreeba.com). It is written on the OpenAPI Specification AKA Swagger. You can find out more about the Open API Initiative at [https://www.openapis.org/](https://www.openapis.org), or more info on Swagger at [http://swagger.io/](http://swagger.io/).
*
* OpenAPI spec version: 1.0.0
* Contact: api@otreeba.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGEdiblesApi: NSObject <SWGApi>

extern NSString* kSWGEdiblesApiErrorDomain;
extern NSInteger kSWGEdiblesApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Find edible by Open Cannabis Product Code (OCPC).
/// Returns a single edible.
///
/// @param ocpc OCPC of the edible to return.
/// 
///  code:200 message:"Successful operation.",
///  code:400 message:"Invalid OCPC supplied.",
///  code:401 message:"Unauthorized action.",
///  code:404 message:"Edible not found."
///
/// @return SWGEdible*
-(NSURLSessionTask*) getEdibleByOcpcWithOcpc: (NSString*) ocpc
    completionHandler: (void (^)(SWGEdible* output, NSError* error)) handler;


/// Get a list of all current edibles.
/// Returns a paginated list of edibles.
///
/// @param page Page to be returned. (optional)
/// @param count The number of items to return. Default 10. Max 50. (optional) (default to 10)
/// @param sort How to sort the items. (optional) (default to -createdAt)
/// 
///  code:200 message:"Successful operation.",
///  code:400 message:"Invalid OCPC supplied.",
///  code:401 message:"Unauthorized action.",
///  code:404 message:"Edible not found."
///
/// @return SWGInlineResponse2002*
-(NSURLSessionTask*) getEdiblesWithPage: (NSNumber*) page
    count: (NSNumber*) count
    sort: (NSString*) sort
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error)) handler;



@end
