=begin
#Otreeba Open Cannabis API

#This is an open, canonical database of cannabis seed companies, strains, brands, products, retailers, and studies from [Otreeba](https://otreeba.com). It is written on the OpenAPI Specification AKA Swagger. You can find out more about the Open API Initiative at [https://www.openapis.org/](https://www.openapis.org), or more info on Swagger at [http://swagger.io/](http://swagger.io/).

OpenAPI spec version: 1.0.0
Contact: api@otreeba.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'date'

module SwaggerClient

  class Product
    # Name of the product.
    attr_accessor :name

    # Open Cannabis Product Code for the product.
    attr_accessor :ocpc

    # Name and Open Cannabis Product Code of the brand that created this product.
    attr_accessor :brand

    # Type of product.
    attr_accessor :type

    # Name and Open Cannabis Product Code of the strain for this product.
    attr_accessor :strain

    # Description of the product.
    attr_accessor :description

    # URL for QR that leads to page on Cannabis Reports.
    attr_accessor :qr

    # URL for the product on Cannabis Reports.
    attr_accessor :url

    # URL for the main photo of the product.
    attr_accessor :image

    # URL for the PDF containing lab testing information for this product.
    attr_accessor :lab_test

    # THC measurement for this product.
    attr_accessor :thc

    # CBD measurement for this product.
    attr_accessor :cbd

    # Cannabis measurement for this product.
    attr_accessor :cannabis

    # Hash oil measurement for this product.
    attr_accessor :hash_oil

    # Date and time record was created, UTC.
    attr_accessor :created_at

    # Date and time record was updated, UTC.
    attr_accessor :updated_at


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'ocpc' => :'ocpc',
        :'brand' => :'brand',
        :'type' => :'type',
        :'strain' => :'strain',
        :'description' => :'description',
        :'qr' => :'qr',
        :'url' => :'url',
        :'image' => :'image',
        :'lab_test' => :'labTest',
        :'thc' => :'thc',
        :'cbd' => :'cbd',
        :'cannabis' => :'cannabis',
        :'hash_oil' => :'hashOil',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'name' => :'String',
        :'ocpc' => :'String',
        :'brand' => :'Object',
        :'type' => :'String',
        :'strain' => :'Object',
        :'description' => :'String',
        :'qr' => :'String',
        :'url' => :'String',
        :'image' => :'String',
        :'lab_test' => :'String',
        :'thc' => :'String',
        :'cbd' => :'String',
        :'cannabis' => :'String',
        :'hash_oil' => :'String',
        :'created_at' => :'DateTime',
        :'updated_at' => :'DateTime'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'ocpc')
        self.ocpc = attributes[:'ocpc']
      end

      if attributes.has_key?(:'brand')
        self.brand = attributes[:'brand']
      end

      if attributes.has_key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.has_key?(:'strain')
        self.strain = attributes[:'strain']
      end

      if attributes.has_key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.has_key?(:'qr')
        self.qr = attributes[:'qr']
      end

      if attributes.has_key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.has_key?(:'image')
        self.image = attributes[:'image']
      end

      if attributes.has_key?(:'labTest')
        self.lab_test = attributes[:'labTest']
      end

      if attributes.has_key?(:'thc')
        self.thc = attributes[:'thc']
      end

      if attributes.has_key?(:'cbd')
        self.cbd = attributes[:'cbd']
      end

      if attributes.has_key?(:'cannabis')
        self.cannabis = attributes[:'cannabis']
      end

      if attributes.has_key?(:'hashOil')
        self.hash_oil = attributes[:'hashOil']
      end

      if attributes.has_key?(:'createdAt')
        self.created_at = attributes[:'createdAt']
      end

      if attributes.has_key?(:'updatedAt')
        self.updated_at = attributes[:'updatedAt']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push("invalid value for 'name', name cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @name.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          ocpc == o.ocpc &&
          brand == o.brand &&
          type == o.type &&
          strain == o.strain &&
          description == o.description &&
          qr == o.qr &&
          url == o.url &&
          image == o.image &&
          lab_test == o.lab_test &&
          thc == o.thc &&
          cbd == o.cbd &&
          cannabis == o.cannabis &&
          hash_oil == o.hash_oil &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [name, ocpc, brand, type, strain, description, qr, url, image, lab_test, thc, cbd, cannabis, hash_oil, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
