/*
 * Otreeba Open Cannabis API
 * This is an open, canonical database of cannabis seed companies, strains, brands, products, retailers, and studies from [Otreeba](https://otreeba.com). It is written on the OpenAPI Specification AKA Swagger. You can find out more about the Open API Initiative at [https://www.openapis.org/](https://www.openapis.org), or more info on Swagger at [http://swagger.io/](http://swagger.io/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@otreeba.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * Product
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-02T20:13:41.059Z")
public class Product {
  @SerializedName("name")
  private String name = null;

  @SerializedName("ocpc")
  private String ocpc = null;

  @SerializedName("brand")
  private Object brand = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("strain")
  private Object strain = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("qr")
  private String qr = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("image")
  private String image = null;

  @SerializedName("labTest")
  private String labTest = null;

  @SerializedName("thc")
  private String thc = null;

  @SerializedName("cbd")
  private String cbd = null;

  @SerializedName("cannabis")
  private String cannabis = null;

  @SerializedName("hashOil")
  private String hashOil = null;

  @SerializedName("createdAt")
  private DateTime createdAt = null;

  @SerializedName("updatedAt")
  private DateTime updatedAt = null;

  public Product name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the product.
   * @return name
  **/
  @ApiModelProperty(example = "X-Pen", required = true, value = "Name of the product.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Product ocpc(String ocpc) {
    this.ocpc = ocpc;
    return this;
  }

   /**
   * Open Cannabis Product Code for the product.
   * @return ocpc
  **/
  @ApiModelProperty(example = "0000000000YPLU3Z2YUM00000", value = "Open Cannabis Product Code for the product.")
  public String getOcpc() {
    return ocpc;
  }

  public void setOcpc(String ocpc) {
    this.ocpc = ocpc;
  }

  public Product brand(Object brand) {
    this.brand = brand;
    return this;
  }

   /**
   * Name and Open Cannabis Product Code of the brand that created this product.
   * @return brand
  **/
  @ApiModelProperty(example = "{&quot;name&quot;:&quot;Elixinol&quot;,&quot;ocpc&quot;:&quot;0000000000YPLU30000000000&quot;}", value = "Name and Open Cannabis Product Code of the brand that created this product.")
  public Object getBrand() {
    return brand;
  }

  public void setBrand(Object brand) {
    this.brand = brand;
  }

  public Product type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of product.
   * @return type
  **/
  @ApiModelProperty(example = "Oil Applicator", value = "Type of product.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Product strain(Object strain) {
    this.strain = strain;
    return this;
  }

   /**
   * Name and Open Cannabis Product Code of the strain for this product.
   * @return strain
  **/
  @ApiModelProperty(example = "{&quot;name&quot;:&quot;Confidential Cheese&quot;,&quot;ocpc&quot;:&quot;TTUYNUF3TP000000000000000&quot;}", value = "Name and Open Cannabis Product Code of the strain for this product.")
  public Object getStrain() {
    return strain;
  }

  public void setStrain(Object strain) {
    this.strain = strain;
  }

  public Product description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the product.
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "Description of the product.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Product qr(String qr) {
    this.qr = qr;
    return this;
  }

   /**
   * URL for QR that leads to page on Cannabis Reports.
   * @return qr
  **/
  @ApiModelProperty(example = "https://www.cannabisreports.com/product-reports/qr-code/elixinol/x-pen.png", value = "URL for QR that leads to page on Cannabis Reports.")
  public String getQr() {
    return qr;
  }

  public void setQr(String qr) {
    this.qr = qr;
  }

  public Product url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL for the product on Cannabis Reports.
   * @return url
  **/
  @ApiModelProperty(example = "https://www.cannabisreports.com/product-reports/elixinol/x-pen", value = "URL for the product on Cannabis Reports.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Product image(String image) {
    this.image = image;
    return this;
  }

   /**
   * URL for the main photo of the product.
   * @return image
  **/
  @ApiModelProperty(example = "https://www.cannabisreports.com/images/products/f/full_f592eb462df530c23a98d0fb6330fc895c8cfe18.jpg", value = "URL for the main photo of the product.")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public Product labTest(String labTest) {
    this.labTest = labTest;
    return this;
  }

   /**
   * URL for the PDF containing lab testing information for this product.
   * @return labTest
  **/
  @ApiModelProperty(example = "https://www.cannabisreports.com/lab-tests/1/140c73d2606fded84e6a14ca07aed77eb1e73827.pdf", value = "URL for the PDF containing lab testing information for this product.")
  public String getLabTest() {
    return labTest;
  }

  public void setLabTest(String labTest) {
    this.labTest = labTest;
  }

  public Product thc(String thc) {
    this.thc = thc;
    return this;
  }

   /**
   * THC measurement for this product.
   * @return thc
  **/
  @ApiModelProperty(example = "0mg", value = "THC measurement for this product.")
  public String getThc() {
    return thc;
  }

  public void setThc(String thc) {
    this.thc = thc;
  }

  public Product cbd(String cbd) {
    this.cbd = cbd;
    return this;
  }

   /**
   * CBD measurement for this product.
   * @return cbd
  **/
  @ApiModelProperty(example = "1,000mg", value = "CBD measurement for this product.")
  public String getCbd() {
    return cbd;
  }

  public void setCbd(String cbd) {
    this.cbd = cbd;
  }

  public Product cannabis(String cannabis) {
    this.cannabis = cannabis;
    return this;
  }

   /**
   * Cannabis measurement for this product.
   * @return cannabis
  **/
  @ApiModelProperty(example = "", value = "Cannabis measurement for this product.")
  public String getCannabis() {
    return cannabis;
  }

  public void setCannabis(String cannabis) {
    this.cannabis = cannabis;
  }

  public Product hashOil(String hashOil) {
    this.hashOil = hashOil;
    return this;
  }

   /**
   * Hash oil measurement for this product.
   * @return hashOil
  **/
  @ApiModelProperty(example = "", value = "Hash oil measurement for this product.")
  public String getHashOil() {
    return hashOil;
  }

  public void setHashOil(String hashOil) {
    this.hashOil = hashOil;
  }

  public Product createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Date and time record was created, UTC.
   * @return createdAt
  **/
  @ApiModelProperty(example = "2014-04-09 09:29:57", value = "Date and time record was created, UTC.")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Product updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Date and time record was updated, UTC.
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2014-04-09 09:29:57", value = "Date and time record was updated, UTC.")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Product product = (Product) o;
    return Objects.equals(this.name, product.name) &&
        Objects.equals(this.ocpc, product.ocpc) &&
        Objects.equals(this.brand, product.brand) &&
        Objects.equals(this.type, product.type) &&
        Objects.equals(this.strain, product.strain) &&
        Objects.equals(this.description, product.description) &&
        Objects.equals(this.qr, product.qr) &&
        Objects.equals(this.url, product.url) &&
        Objects.equals(this.image, product.image) &&
        Objects.equals(this.labTest, product.labTest) &&
        Objects.equals(this.thc, product.thc) &&
        Objects.equals(this.cbd, product.cbd) &&
        Objects.equals(this.cannabis, product.cannabis) &&
        Objects.equals(this.hashOil, product.hashOil) &&
        Objects.equals(this.createdAt, product.createdAt) &&
        Objects.equals(this.updatedAt, product.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, ocpc, brand, type, strain, description, qr, url, image, labTest, thc, cbd, cannabis, hashOil, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Product {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ocpc: ").append(toIndentedString(ocpc)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    strain: ").append(toIndentedString(strain)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    qr: ").append(toIndentedString(qr)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    labTest: ").append(toIndentedString(labTest)).append("\n");
    sb.append("    thc: ").append(toIndentedString(thc)).append("\n");
    sb.append("    cbd: ").append(toIndentedString(cbd)).append("\n");
    sb.append("    cannabis: ").append(toIndentedString(cannabis)).append("\n");
    sb.append("    hashOil: ").append(toIndentedString(hashOil)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

