/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Product (
  /* Name of the product. */
  name: String,
  /* Open Cannabis Product Code for the product. */
  ocpc: Option[String],
  /* Name and Open Cannabis Product Code of the brand that created this product. */
  brand: Option[Any],
  /* Type of product. */
  `type`: Option[String],
  /* Name and Open Cannabis Product Code of the strain for this product. */
  strain: Option[Any],
  /* Description of the product. */
  description: Option[String],
  /* URL for QR that leads to page on Cannabis Reports. */
  qr: Option[String],
  /* URL for the product on Cannabis Reports. */
  url: Option[String],
  /* URL for the main photo of the product. */
  image: Option[String],
  /* URL for the PDF containing lab testing information for this product. */
  labTest: Option[String],
  /* THC measurement for this product. */
  thc: Option[String],
  /* CBD measurement for this product. */
  cbd: Option[String],
  /* Cannabis measurement for this product. */
  cannabis: Option[String],
  /* Hash oil measurement for this product. */
  hashOil: Option[String],
  /* Date and time record was created, UTC. */
  createdAt: Option[DateTime],
  /* Date and time record was updated, UTC. */
  updatedAt: Option[DateTime]
) extends ApiModel


