/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class SeedCompany (
  /* Name of the seed company. */
  name: String,
  /* Open Cannabis Product Code for the seed company. */
  ocpc: Option[String],
  /* URL for QR that leads to page on Cannabis Reports. */
  qr: Option[String],
  /* URL for seed company on Cannabis Reports. */
  url: Option[String],
  /* URL for logo for seed company. */
  image: Option[String],
  /* Object of countries that this seed company has lineages from. {'Country Name' => 'ISO 3166-1 Two Letter Country Code'} */
  lineage: Option[Any],
  /* OCPCs of the strains from this seed company. */
  strains: Option[Seq[String]],
  /* Date and time record was created, UTC. */
  createdAt: Option[DateTime],
  /* Date and time record was updated, UTC. */
  updatedAt: Option[DateTime]
) extends ApiModel


