#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Otreeba Open Cannabis API
* This is an open, canonical database of cannabis seed companies, strains, brands, products, retailers, and studies from [Otreeba](https://otreeba.com). It is written on the OpenAPI Specification AKA Swagger. You can find out more about the Open API Initiative at [https://www.openapis.org/](https://www.openapis.org), or more info on Swagger at [http://swagger.io/](http://swagger.io/).
*
* OpenAPI spec version: 1.0.0
* Contact: api@otreeba.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGBrand
@end

@interface SWGBrand : SWGObject

/* Name of the brand. 
 */
@property(nonatomic) NSString* name;
/* Open Cannabis Product Code for the brand. [optional]
 */
@property(nonatomic) NSString* ocpc;
/* URL for brand on Otreeba. [optional]
 */
@property(nonatomic) NSString* link;
/* URL for QR that leads to page on Cannabis Reports. [optional]
 */
@property(nonatomic) NSString* qr;
/* URL for brand on Cannabis Reports. [optional]
 */
@property(nonatomic) NSString* url;
/* URL for logo for brand. [optional]
 */
@property(nonatomic) NSString* image;
/* OCPCs of the flowers from this brand. [optional]
 */
@property(nonatomic) NSArray<NSString*>* flowers;
/* OCPCs of the extracts from this brand. [optional]
 */
@property(nonatomic) NSArray<NSString*>* extracts;
/* OCPCs of the edibles from this brand. [optional]
 */
@property(nonatomic) NSArray<NSString*>* edibles;
/* OCPCs of the products from this brand. [optional]
 */
@property(nonatomic) NSArray<NSString*>* products;
/* Date and time record was created, UTC. [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* Date and time record was updated, UTC. [optional]
 */
@property(nonatomic) NSDate* updatedAt;

@end
