#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Otreeba Open Cannabis API
* This is an open, canonical database of cannabis seed companies, strains, brands, products, retailers, and studies from [Otreeba](https://otreeba.com). It is written on the OpenAPI Specification AKA Swagger. You can find out more about the Open API Initiative at [https://www.openapis.org/](https://www.openapis.org), or more info on Swagger at [http://swagger.io/](http://swagger.io/).
*
* OpenAPI spec version: 1.0.0
* Contact: api@otreeba.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGFlower
@end

@interface SWGFlower : SWGObject

/* Name of the flowers. 
 */
@property(nonatomic) NSString* name;
/* Open Cannabis Product Code for the flowers. [optional]
 */
@property(nonatomic) NSString* ocpc;
/* Name and Open Cannabis Product Code of the brand that created these flowers. [optional]
 */
@property(nonatomic) NSObject* brand;
/* Type of flowers. [optional]
 */
@property(nonatomic) NSString* type;
/* Name and Open Cannabis Product Code of the strain for these flowers. [optional]
 */
@property(nonatomic) NSObject* strain;
/* Description of the flowers. [optional]
 */
@property(nonatomic) NSString* _description;
/* URL for QR that leads to page on Cannabis Reports. [optional]
 */
@property(nonatomic) NSString* qr;
/* URL for the flowers on Cannabis Reports. [optional]
 */
@property(nonatomic) NSString* url;
/* URL for the main photo of the flowers. [optional]
 */
@property(nonatomic) NSString* image;
/* URL for the PDF containing lab testing information for these flowers. [optional]
 */
@property(nonatomic) NSString* labTest;
/* THC measurement for these flowers. [optional]
 */
@property(nonatomic) NSString* thc;
/* CBD measurement for these flowers. [optional]
 */
@property(nonatomic) NSString* cbd;
/* Date and time record was created, UTC. [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* Date and time record was updated, UTC. [optional]
 */
@property(nonatomic) NSDate* updatedAt;

@end
