=begin comment

Otreeba Open Cannabis API

This is an open, canonical database of cannabis seed companies, strains, brands, products, retailers, and studies from [Otreeba](https://otreeba.com). It is written on the OpenAPI Specification AKA Swagger. You can find out more about the Open API Initiative at [https://www.openapis.org/](https://www.openapis.org), or more info on Swagger at [http://swagger.io/](http://swagger.io/).

OpenAPI spec version: 1.0.0
Contact: api@otreeba.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::ExtractsApi');

my $api = WWW::SwaggerClient::ExtractsApi->new();
isa_ok($api, 'WWW::SwaggerClient::ExtractsApi');

#
# get_extract_by_ocpc test
#
{
    my $ocpc = undef; # replace NULL with a proper value
    my $result = $api->get_extract_by_ocpc(ocpc => $ocpc);
}

#
# get_extracts test
#
{
    my $page = undef; # replace NULL with a proper value
    my $count = undef; # replace NULL with a proper value
    my $sort = undef; # replace NULL with a proper value
    my $result = $api->get_extracts(page => $page, count => $count, sort => $sort);
}


1;
