/* 
 * Otreeba Open Cannabis API
 *
 * This is an open, canonical database of cannabis seed companies, strains, brands, products, retailers, and studies from [Otreeba](https://otreeba.com). It is written on the OpenAPI Specification AKA Swagger. You can find out more about the Open API Initiative at [https://www.openapis.org/](https://www.openapis.org), or more info on Swagger at [http://swagger.io/](http://swagger.io/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@otreeba.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SeedCompaniesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SeedCompaniesApiTests
    {
        private SeedCompaniesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SeedCompaniesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SeedCompaniesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SeedCompaniesApi
            //Assert.IsInstanceOfType(typeof(SeedCompaniesApi), instance, "instance is a SeedCompaniesApi");
        }

        
        /// <summary>
        /// Test GetSeedCompanies
        /// </summary>
        [Test]
        public void GetSeedCompaniesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? count = null;
            //string sort = null;
            //var response = instance.GetSeedCompanies(page, count, sort);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        
        /// <summary>
        /// Test GetSeedCompanyByOcpc
        /// </summary>
        [Test]
        public void GetSeedCompanyByOcpcTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ocpc = null;
            //var response = instance.GetSeedCompanyByOcpc(ocpc);
            //Assert.IsInstanceOf<SeedCompany> (response, "response is SeedCompany");
        }
        
        /// <summary>
        /// Test GetSeedCompanyStrainsByOcpc
        /// </summary>
        [Test]
        public void GetSeedCompanyStrainsByOcpcTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ocpc = null;
            //int? page = null;
            //int? count = null;
            //var response = instance.GetSeedCompanyStrainsByOcpc(ocpc, page, count);
            //Assert.IsInstanceOf<InlineResponse2001> (response, "response is InlineResponse2001");
        }
        
    }

}
