/* 
 * Otreeba Open Cannabis API
 *
 * This is an open, canonical database of cannabis seed companies, strains, brands, products, retailers, and studies from [Otreeba](https://otreeba.com). It is written on the OpenAPI Specification AKA Swagger. You can find out more about the Open API Initiative at [https://www.openapis.org/](https://www.openapis.org), or more info on Swagger at [http://swagger.io/](http://swagger.io/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@otreeba.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IExtractsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Find extract by Open Cannabis Product Code (OCPC).
        /// </summary>
        /// <remarks>
        /// Returns a single extract.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ocpc">OCPC of the extract to return.</param>
        /// <returns>Extract</returns>
        Extract GetExtractByOcpc (string ocpc);

        /// <summary>
        /// Find extract by Open Cannabis Product Code (OCPC).
        /// </summary>
        /// <remarks>
        /// Returns a single extract.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ocpc">OCPC of the extract to return.</param>
        /// <returns>ApiResponse of Extract</returns>
        ApiResponse<Extract> GetExtractByOcpcWithHttpInfo (string ocpc);
        /// <summary>
        /// Get a list of all current extracts.
        /// </summary>
        /// <remarks>
        /// Returns a paginated list of extracts.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page to be returned. (optional)</param>
        /// <param name="count">The number of items to return. Default 10. Max 50. (optional, default to 10)</param>
        /// <param name="sort">How to sort the items. (optional, default to -createdAt)</param>
        /// <returns>InlineResponse2003</returns>
        InlineResponse2003 GetExtracts (int? page = null, int? count = null, string sort = null);

        /// <summary>
        /// Get a list of all current extracts.
        /// </summary>
        /// <remarks>
        /// Returns a paginated list of extracts.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page to be returned. (optional)</param>
        /// <param name="count">The number of items to return. Default 10. Max 50. (optional, default to 10)</param>
        /// <param name="sort">How to sort the items. (optional, default to -createdAt)</param>
        /// <returns>ApiResponse of InlineResponse2003</returns>
        ApiResponse<InlineResponse2003> GetExtractsWithHttpInfo (int? page = null, int? count = null, string sort = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Find extract by Open Cannabis Product Code (OCPC).
        /// </summary>
        /// <remarks>
        /// Returns a single extract.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ocpc">OCPC of the extract to return.</param>
        /// <returns>Task of Extract</returns>
        System.Threading.Tasks.Task<Extract> GetExtractByOcpcAsync (string ocpc);

        /// <summary>
        /// Find extract by Open Cannabis Product Code (OCPC).
        /// </summary>
        /// <remarks>
        /// Returns a single extract.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ocpc">OCPC of the extract to return.</param>
        /// <returns>Task of ApiResponse (Extract)</returns>
        System.Threading.Tasks.Task<ApiResponse<Extract>> GetExtractByOcpcAsyncWithHttpInfo (string ocpc);
        /// <summary>
        /// Get a list of all current extracts.
        /// </summary>
        /// <remarks>
        /// Returns a paginated list of extracts.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page to be returned. (optional)</param>
        /// <param name="count">The number of items to return. Default 10. Max 50. (optional, default to 10)</param>
        /// <param name="sort">How to sort the items. (optional, default to -createdAt)</param>
        /// <returns>Task of InlineResponse2003</returns>
        System.Threading.Tasks.Task<InlineResponse2003> GetExtractsAsync (int? page = null, int? count = null, string sort = null);

        /// <summary>
        /// Get a list of all current extracts.
        /// </summary>
        /// <remarks>
        /// Returns a paginated list of extracts.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page to be returned. (optional)</param>
        /// <param name="count">The number of items to return. Default 10. Max 50. (optional, default to 10)</param>
        /// <param name="sort">How to sort the items. (optional, default to -createdAt)</param>
        /// <returns>Task of ApiResponse (InlineResponse2003)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse2003>> GetExtractsAsyncWithHttpInfo (int? page = null, int? count = null, string sort = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ExtractsApi : IExtractsApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ExtractsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ExtractsApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExtractsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ExtractsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Find extract by Open Cannabis Product Code (OCPC). Returns a single extract.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ocpc">OCPC of the extract to return.</param>
        /// <returns>Extract</returns>
        public Extract GetExtractByOcpc (string ocpc)
        {
             ApiResponse<Extract> localVarResponse = GetExtractByOcpcWithHttpInfo(ocpc);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Find extract by Open Cannabis Product Code (OCPC). Returns a single extract.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ocpc">OCPC of the extract to return.</param>
        /// <returns>ApiResponse of Extract</returns>
        public ApiResponse< Extract > GetExtractByOcpcWithHttpInfo (string ocpc)
        {
            // verify the required parameter 'ocpc' is set
            if (ocpc == null)
                throw new ApiException(400, "Missing required parameter 'ocpc' when calling ExtractsApi->GetExtractByOcpc");

            var localVarPath = "/extracts/{ocpc}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ocpc != null) localVarPathParams.Add("ocpc", Configuration.ApiClient.ParameterToString(ocpc)); // path parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarHeaderParams["X-API-Key"] = Configuration.GetApiKeyWithPrefix("X-API-Key");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetExtractByOcpc", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Extract>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Extract) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Extract)));
        }

        /// <summary>
        /// Find extract by Open Cannabis Product Code (OCPC). Returns a single extract.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ocpc">OCPC of the extract to return.</param>
        /// <returns>Task of Extract</returns>
        public async System.Threading.Tasks.Task<Extract> GetExtractByOcpcAsync (string ocpc)
        {
             ApiResponse<Extract> localVarResponse = await GetExtractByOcpcAsyncWithHttpInfo(ocpc);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Find extract by Open Cannabis Product Code (OCPC). Returns a single extract.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ocpc">OCPC of the extract to return.</param>
        /// <returns>Task of ApiResponse (Extract)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Extract>> GetExtractByOcpcAsyncWithHttpInfo (string ocpc)
        {
            // verify the required parameter 'ocpc' is set
            if (ocpc == null)
                throw new ApiException(400, "Missing required parameter 'ocpc' when calling ExtractsApi->GetExtractByOcpc");

            var localVarPath = "/extracts/{ocpc}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ocpc != null) localVarPathParams.Add("ocpc", Configuration.ApiClient.ParameterToString(ocpc)); // path parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarHeaderParams["X-API-Key"] = Configuration.GetApiKeyWithPrefix("X-API-Key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetExtractByOcpc", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Extract>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Extract) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Extract)));
        }

        /// <summary>
        /// Get a list of all current extracts. Returns a paginated list of extracts.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page to be returned. (optional)</param>
        /// <param name="count">The number of items to return. Default 10. Max 50. (optional, default to 10)</param>
        /// <param name="sort">How to sort the items. (optional, default to -createdAt)</param>
        /// <returns>InlineResponse2003</returns>
        public InlineResponse2003 GetExtracts (int? page = null, int? count = null, string sort = null)
        {
             ApiResponse<InlineResponse2003> localVarResponse = GetExtractsWithHttpInfo(page, count, sort);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a list of all current extracts. Returns a paginated list of extracts.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page to be returned. (optional)</param>
        /// <param name="count">The number of items to return. Default 10. Max 50. (optional, default to 10)</param>
        /// <param name="sort">How to sort the items. (optional, default to -createdAt)</param>
        /// <returns>ApiResponse of InlineResponse2003</returns>
        public ApiResponse< InlineResponse2003 > GetExtractsWithHttpInfo (int? page = null, int? count = null, string sort = null)
        {

            var localVarPath = "/extracts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (page != null) localVarQueryParams.Add("page", Configuration.ApiClient.ParameterToString(page)); // query parameter
            if (count != null) localVarQueryParams.Add("count", Configuration.ApiClient.ParameterToString(count)); // query parameter
            if (sort != null) localVarQueryParams.Add("sort", Configuration.ApiClient.ParameterToString(sort)); // query parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarHeaderParams["X-API-Key"] = Configuration.GetApiKeyWithPrefix("X-API-Key");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetExtracts", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse2003>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InlineResponse2003) Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse2003)));
        }

        /// <summary>
        /// Get a list of all current extracts. Returns a paginated list of extracts.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page to be returned. (optional)</param>
        /// <param name="count">The number of items to return. Default 10. Max 50. (optional, default to 10)</param>
        /// <param name="sort">How to sort the items. (optional, default to -createdAt)</param>
        /// <returns>Task of InlineResponse2003</returns>
        public async System.Threading.Tasks.Task<InlineResponse2003> GetExtractsAsync (int? page = null, int? count = null, string sort = null)
        {
             ApiResponse<InlineResponse2003> localVarResponse = await GetExtractsAsyncWithHttpInfo(page, count, sort);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a list of all current extracts. Returns a paginated list of extracts.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page to be returned. (optional)</param>
        /// <param name="count">The number of items to return. Default 10. Max 50. (optional, default to 10)</param>
        /// <param name="sort">How to sort the items. (optional, default to -createdAt)</param>
        /// <returns>Task of ApiResponse (InlineResponse2003)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<InlineResponse2003>> GetExtractsAsyncWithHttpInfo (int? page = null, int? count = null, string sort = null)
        {

            var localVarPath = "/extracts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (page != null) localVarQueryParams.Add("page", Configuration.ApiClient.ParameterToString(page)); // query parameter
            if (count != null) localVarQueryParams.Add("count", Configuration.ApiClient.ParameterToString(count)); // query parameter
            if (sort != null) localVarQueryParams.Add("sort", Configuration.ApiClient.ParameterToString(sort)); // query parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarHeaderParams["X-API-Key"] = Configuration.GetApiKeyWithPrefix("X-API-Key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetExtracts", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InlineResponse2003>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InlineResponse2003) Configuration.ApiClient.Deserialize(localVarResponse, typeof(InlineResponse2003)));
        }

    }
}
