/**
 * Otreeba Open Cannabis API
 * This is an open, canonical database of cannabis seed companies, strains, brands, products, retailers, and studies from [Otreeba](https://otreeba.com). It is written on the OpenAPI Specification AKA Swagger. You can find out more about the Open API Initiative at [https://www.openapis.org/](https://www.openapis.org), or more info on Swagger at [http://swagger.io/](http://swagger.io/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@otreeba.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.api;

import io.swagger.model.Flower;
import io.swagger.model.InlineResponse2004;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * API tests for FlowersApi
 */
public class FlowersApiTest {


    private FlowersApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("https://api.otreeba.com/v1", FlowersApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    
    /**
     * Find flower by Open Cannabis Product Code (OCPC).
     *
     * Returns a single flower.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFlowerByOcpcTest() {
        String ocpc = null;
        //Flower response = api.getFlowerByOcpc(ocpc);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Get a list of all current flowers.
     *
     * Returns a paginated list of flowers.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFlowersTest() {
        Integer page = null;
        Integer count = null;
        String sort = null;
        //InlineResponse2004 response = api.getFlowers(page, count, sort);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
}
