/* 
 * Otreeba Open Cannabis API
 *
 * This is an open, canonical database of cannabis seed companies, strains, brands, products, retailers, and studies from [Otreeba](https://otreeba.com). It is written on the OpenAPI Specification AKA Swagger. You can find out more about the Open API Initiative at [https://www.openapis.org/](https://www.openapis.org), or more info on Swagger at [http://swagger.io/](http://swagger.io/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@otreeba.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Pagination struct {

	// Total number of results available.
	Total int32 `json:"total,omitempty"`

	// Number of results to return. Default 10. Max 50.
	Count int32 `json:"count,omitempty"`

	// Number of results per page.
	PerPage int32 `json:"per_page,omitempty"`

	// Page of results.
	CurrentPage int32 `json:"current_page,omitempty"`

	// Total number of pages of results.
	TotalPages int32 `json:"total_pages,omitempty"`

	// Links to the previous and/or next pages of results.
	Links interface{} `json:"links,omitempty"`
}
