# coding: utf-8

"""
    Otreeba Open Cannabis API

    This is an open, canonical database of cannabis seed companies, strains, brands, products, retailers, and studies from [Otreeba](https://otreeba.com). It is written on the OpenAPI Specification AKA Swagger. You can find out more about the Open API Initiative at [https://www.openapis.org/](https://www.openapis.org), or more info on Swagger at [http://swagger.io/](http://swagger.io/).

    OpenAPI spec version: 1.0.0
    Contact: api@otreeba.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Product(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, ocpc=None, brand=None, type=None, strain=None, description=None, qr=None, url=None, image=None, lab_test=None, thc=None, cbd=None, cannabis=None, hash_oil=None, created_at=None, updated_at=None):
        """
        Product - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'ocpc': 'str',
            'brand': 'object',
            'type': 'str',
            'strain': 'object',
            'description': 'str',
            'qr': 'str',
            'url': 'str',
            'image': 'str',
            'lab_test': 'str',
            'thc': 'str',
            'cbd': 'str',
            'cannabis': 'str',
            'hash_oil': 'str',
            'created_at': 'datetime',
            'updated_at': 'datetime'
        }

        self.attribute_map = {
            'name': 'name',
            'ocpc': 'ocpc',
            'brand': 'brand',
            'type': 'type',
            'strain': 'strain',
            'description': 'description',
            'qr': 'qr',
            'url': 'url',
            'image': 'image',
            'lab_test': 'labTest',
            'thc': 'thc',
            'cbd': 'cbd',
            'cannabis': 'cannabis',
            'hash_oil': 'hashOil',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }

        self._name = name
        self._ocpc = ocpc
        self._brand = brand
        self._type = type
        self._strain = strain
        self._description = description
        self._qr = qr
        self._url = url
        self._image = image
        self._lab_test = lab_test
        self._thc = thc
        self._cbd = cbd
        self._cannabis = cannabis
        self._hash_oil = hash_oil
        self._created_at = created_at
        self._updated_at = updated_at

    @property
    def name(self):
        """
        Gets the name of this Product.
        Name of the product.

        :return: The name of this Product.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Product.
        Name of the product.

        :param name: The name of this Product.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def ocpc(self):
        """
        Gets the ocpc of this Product.
        Open Cannabis Product Code for the product.

        :return: The ocpc of this Product.
        :rtype: str
        """
        return self._ocpc

    @ocpc.setter
    def ocpc(self, ocpc):
        """
        Sets the ocpc of this Product.
        Open Cannabis Product Code for the product.

        :param ocpc: The ocpc of this Product.
        :type: str
        """

        self._ocpc = ocpc

    @property
    def brand(self):
        """
        Gets the brand of this Product.
        Name and Open Cannabis Product Code of the brand that created this product.

        :return: The brand of this Product.
        :rtype: object
        """
        return self._brand

    @brand.setter
    def brand(self, brand):
        """
        Sets the brand of this Product.
        Name and Open Cannabis Product Code of the brand that created this product.

        :param brand: The brand of this Product.
        :type: object
        """

        self._brand = brand

    @property
    def type(self):
        """
        Gets the type of this Product.
        Type of product.

        :return: The type of this Product.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Product.
        Type of product.

        :param type: The type of this Product.
        :type: str
        """

        self._type = type

    @property
    def strain(self):
        """
        Gets the strain of this Product.
        Name and Open Cannabis Product Code of the strain for this product.

        :return: The strain of this Product.
        :rtype: object
        """
        return self._strain

    @strain.setter
    def strain(self, strain):
        """
        Sets the strain of this Product.
        Name and Open Cannabis Product Code of the strain for this product.

        :param strain: The strain of this Product.
        :type: object
        """

        self._strain = strain

    @property
    def description(self):
        """
        Gets the description of this Product.
        Description of the product.

        :return: The description of this Product.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this Product.
        Description of the product.

        :param description: The description of this Product.
        :type: str
        """

        self._description = description

    @property
    def qr(self):
        """
        Gets the qr of this Product.
        URL for QR that leads to page on Cannabis Reports.

        :return: The qr of this Product.
        :rtype: str
        """
        return self._qr

    @qr.setter
    def qr(self, qr):
        """
        Sets the qr of this Product.
        URL for QR that leads to page on Cannabis Reports.

        :param qr: The qr of this Product.
        :type: str
        """

        self._qr = qr

    @property
    def url(self):
        """
        Gets the url of this Product.
        URL for the product on Cannabis Reports.

        :return: The url of this Product.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """
        Sets the url of this Product.
        URL for the product on Cannabis Reports.

        :param url: The url of this Product.
        :type: str
        """

        self._url = url

    @property
    def image(self):
        """
        Gets the image of this Product.
        URL for the main photo of the product.

        :return: The image of this Product.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """
        Sets the image of this Product.
        URL for the main photo of the product.

        :param image: The image of this Product.
        :type: str
        """

        self._image = image

    @property
    def lab_test(self):
        """
        Gets the lab_test of this Product.
        URL for the PDF containing lab testing information for this product.

        :return: The lab_test of this Product.
        :rtype: str
        """
        return self._lab_test

    @lab_test.setter
    def lab_test(self, lab_test):
        """
        Sets the lab_test of this Product.
        URL for the PDF containing lab testing information for this product.

        :param lab_test: The lab_test of this Product.
        :type: str
        """

        self._lab_test = lab_test

    @property
    def thc(self):
        """
        Gets the thc of this Product.
        THC measurement for this product.

        :return: The thc of this Product.
        :rtype: str
        """
        return self._thc

    @thc.setter
    def thc(self, thc):
        """
        Sets the thc of this Product.
        THC measurement for this product.

        :param thc: The thc of this Product.
        :type: str
        """

        self._thc = thc

    @property
    def cbd(self):
        """
        Gets the cbd of this Product.
        CBD measurement for this product.

        :return: The cbd of this Product.
        :rtype: str
        """
        return self._cbd

    @cbd.setter
    def cbd(self, cbd):
        """
        Sets the cbd of this Product.
        CBD measurement for this product.

        :param cbd: The cbd of this Product.
        :type: str
        """

        self._cbd = cbd

    @property
    def cannabis(self):
        """
        Gets the cannabis of this Product.
        Cannabis measurement for this product.

        :return: The cannabis of this Product.
        :rtype: str
        """
        return self._cannabis

    @cannabis.setter
    def cannabis(self, cannabis):
        """
        Sets the cannabis of this Product.
        Cannabis measurement for this product.

        :param cannabis: The cannabis of this Product.
        :type: str
        """

        self._cannabis = cannabis

    @property
    def hash_oil(self):
        """
        Gets the hash_oil of this Product.
        Hash oil measurement for this product.

        :return: The hash_oil of this Product.
        :rtype: str
        """
        return self._hash_oil

    @hash_oil.setter
    def hash_oil(self, hash_oil):
        """
        Sets the hash_oil of this Product.
        Hash oil measurement for this product.

        :param hash_oil: The hash_oil of this Product.
        :type: str
        """

        self._hash_oil = hash_oil

    @property
    def created_at(self):
        """
        Gets the created_at of this Product.
        Date and time record was created, UTC.

        :return: The created_at of this Product.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this Product.
        Date and time record was created, UTC.

        :param created_at: The created_at of this Product.
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """
        Gets the updated_at of this Product.
        Date and time record was updated, UTC.

        :return: The updated_at of this Product.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """
        Sets the updated_at of this Product.
        Date and time record was updated, UTC.

        :param updated_at: The updated_at of this Product.
        :type: datetime
        """

        self._updated_at = updated_at

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Product):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
